// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zolupos.Modules.Transactions.Infrastructure.Context;

#nullable disable

namespace Zolupos.Modules.Transactions.Infrastructure.Migrations
{
    [DbContext(typeof(TransactionsContext))]
    [Migration("20220515082851_Migration 05-15-2022-16-28")]
    partial class Migration051520221628
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zolupos.Modules.Transactions.Core.Entities.OrderedItems", b =>
                {
                    b.Property<int>("OrderedItemsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderedItemsId"));

                    b.Property<int>("OrderTransactionsId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductOrderedId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductOrderedQuantity")
                        .HasColumnType("integer");

                    b.Property<bool>("isProductReturned")
                        .HasColumnType("boolean");

                    b.HasKey("OrderedItemsId");

                    b.HasIndex("OrderTransactionsId");

                    b.ToTable("OrderedItems");
                });

            modelBuilder.Entity("Zolupos.Modules.Transactions.Core.Entities.OrderTransactions", b =>
                {
                    b.Property<int>("OrderTransactionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderTransactionsId"));

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderTransactionsId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Zolupos.Modules.Transactions.Core.Entities.OrderedItems", b =>
                {
                    b.HasOne("Zolupos.Modules.Transactions.Core.Entities.OrderTransactions", "OrderTransactions")
                        .WithMany("OrderedItems")
                        .HasForeignKey("OrderTransactionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderTransactions");
                });

            modelBuilder.Entity("Zolupos.Modules.Transactions.Core.Entities.OrderTransactions", b =>
                {
                    b.Navigation("OrderedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
